FROM node:22

WORKDIR /app

RUN npm install body-parser custom-env mongoose cors express jsonwebtoken concurrently bcryptjs multer

COPY webServer/ .
COPY webServer/config/.env.local ./config/.env.local

EXPOSE ${PORT}

CMD ["node", "app.js"]